local M = {
    plugin_config = {
        kbrd_cmd = "xkb-switch -s ",
        spell_files_folder = os.getenv("HOME") .. "/.config/nvim/spell/",
    },
    base_config = {
        mode_language = {
            active = false,
            file_types = {
                black_list = {
                    "alpha",
                    "ctrlspace",
                    "ctrlspace_help",
                    "packer",
                    "undotree",
                    "diff",
                    "Outline",
                    "NvimTree",
                    "LvimHelper",
                    "floaterm",
                    "toggleterm",
                    "Trouble",
                    "dashboard",
                    "vista",
                    "spectre_panel",
                    "DiffviewFiles",
                    "flutterToolsOutline",
                    "log",
                    "qf",
                    "dapui_scopes",
                    "dapui_breakpoints",
                    "dapui_stacks",
                    "dapui_watches",
                    "calendar",
                    "octo",
                    "neo-tree",
                    "neo-tree-popup",
                    "noice",
                },
                white_list = {},
            },
            normal_mode_language = nil,
            insert_mode_language = nil,
            insert_mode_languages = {},
        },
        spell = {
            active = false,
            file_types = {
                black_list = {
                    "alpha",
                    "ctrlspace",
                    "ctrlspace_help",
                    "packer",
                    "undotree",
                    "diff",
                    "Outline",
                    "NvimTree",
                    "LvimHelper",
                    "floaterm",
                    "toggleterm",
                    "Trouble",
                    "dashboard",
                    "vista",
                    "spectre_panel",
                    "DiffviewFiles",
                    "flutterToolsOutline",
                    "log",
                    "qf",
                    "dapui_scopes",
                    "dapui_breakpoints",
                    "dapui_stacks",
                    "dapui_watches",
                    "calendar",
                    "octo",
                    "neo-tree",
                    "neo-tree-popup",
                    "noice",
                },
                white_list = {},
            },
            language = nil,
            languages = {
                en = {
                    spelllang = "en",
                    spellfile = "en.add",
                },
            },
        },
    },
}

return M
